"""
Django settings for expenses project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from decouple import config
import dj_database_url

logger = logging.getLogger(__name__)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Accepts both SECRET_KEY and DJANGO_SECRET_KEY for backwards compatibility
SECRET_KEY = config('SECRET_KEY', default=config('DJANGO_SECRET_KEY', default=''))
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY không được để trống. "
        "Đặt biến môi trường SECRET_KEY hoặc DJANGO_SECRET_KEY."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False') in ['True', 'true', '1', True]

# ALLOWED_HOSTS — không dùng wildcard trong production
# Render tự inject RENDER_EXTERNAL_HOSTNAME; local dev dùng localhost
_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
_extra_hosts = config('ALLOWED_HOSTS', default='').split(',')
ALLOWED_HOSTS = list(filter(None, [
    'localhost',
    '127.0.0.1',
    _render_hostname,
] + _extra_hosts))

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ── Production Security Settings ──────────────────────────────────────────────
# Chỉ bật khi DEBUG=False để không ảnh hưởng local development
if not DEBUG:
    # Redirect HTTP → HTTPS
    SECURE_SSL_REDIRECT = True
    # Trust X-Forwarded-Proto từ Render/reverse proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS: 1 năm, bao gồm subdomain, sẵn sàng preload
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Bảo vệ content sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'cloudinary_storage',  
    'django.contrib.staticfiles',
    'cloudinary',
    'app_expenses.apps.AppExpensesConfig',
    'widget_tweaks',
    # 'django_cleanup.apps.CleanupConfig' # Đã tắt vì không tương thích với CloudinaryField, dùng signal thay thế
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - supports both MySQL and PostgreSQL
database_url = config('DATABASE_URL', default=None)
if database_url:
    DATABASES = {'default': dj_database_url.parse(database_url)}
else:
    # Use environment variables for database config
    db_engine = config('DATABASE_ENGINE', default='django.db.backends.mysql')
    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': config('DATABASE_NAME', default=config('DB_NAME', default='expenses_db')),
            'USER': config('DATABASE_USER', default=config('DB_USER', default='root')),
            'PASSWORD': config('DATABASE_PASSWORD', default=config('DB_PASSWORD', default='')),
            'HOST': config('DATABASE_HOST', default=config('DB_HOST', default='127.0.0.1')),
            'PORT': config('DATABASE_PORT', default=config('DB_PORT', default='3306')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'app_expenses.validators.VietnameseMinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True  # Required for intcomma filter

USE_TZ = True

# Ép sử dụng dấu phẩy cho hàng nghìn
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ','
DECIMAL_SEPARATOR = '.'
NUMBER_GROUPING = 3  # Group by 3 digits

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Note: STATICFILES_DIRS is not needed here because Django's AppDirectoriesFinder
# automatically discovers static files in app_expenses/static/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'app_expenses': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Cấu hình lưu trữ file media (ảnh upload từ user)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files storage
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Cloudinary configuration for media files (avatars, etc.)
import cloudinary
import cloudinary.uploader
import cloudinary.api
import os

# Ưu tiên dùng CLOUDINARY_URL nếu có (format: cloudinary://api_key:api_secret@cloud_name)
CLOUDINARY_URL = config('CLOUDINARY_URL', default='')
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')

# Set environment variable for cloudinary library to auto-load
if CLOUDINARY_URL:
    os.environ['CLOUDINARY_URL'] = CLOUDINARY_URL

# Configure cloudinary explicitly
cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True
)

# Use Cloudinary for media storage if configured
if CLOUDINARY_CLOUD_NAME:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    
    # Cloudinary storage settings
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
        'SECURE': True,
        'MEDIA_TAG': 'media',
        'INVALID_VIDEO_ERROR_MESSAGE': 'Please upload a valid video file.',
        'EXCLUDE_DELETE_ORPHANED_MEDIA_PATHS': (),
        'STATIC_TAG': 'static',
    }
else:
    # Use local storage for development
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Email configuration
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

# Email configuration
EMAIL_HOST = config('EMAIL_HOST', default='').strip()

if EMAIL_HOST:
    import ssl
    import certifi

    # Set SSL cert location for macOS compatibility
    os.environ['SSL_CERT_FILE'] = certifi.where()

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default='True') in ['True', 'true', '1', True]
    EMAIL_USE_SSL = config('EMAIL_USE_SSL', default='False') in ['True', 'true', '1', True]
    EMAIL_TIMEOUT = 10
    logger.debug("Email backend: SMTP (%s:%s)", EMAIL_HOST, config('EMAIL_PORT', default=587))
else:
    # Development: print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    logger.debug("Email backend: console (EMAIL_HOST is empty)")