# Generated by Django 5.2 on 2025-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep1', '0004_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('priority', models.CharField(choices=[('info', 'Thông tin (Xanh dương)'), ('success', 'Thành công (Xanh lá)'), ('warning', 'Cảnh báo (Vàng)'), ('danger', 'Khẩn cấp (Đỏ)')], default='info', max_length=10, verbose_name='Loại thông báo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
