# Generated by Django 5.2 on 2025-12-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep1', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
