# Generated by Django 5.2 on 2026-03-08 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep1', '0009_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(help_text='Ví dụ: Mua Macbook, Du lịch Nhật Bản, ...', max_length=200, verbose_name='Tên mục tiêu')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Số tiền bạn muốn tiết kiệm', max_digits=15, verbose_name='Số tiền mục tiêu')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền đã tiết kiệm được', max_digits=15, verbose_name='Số tiền hiện tại')),
                ('start_date', models.DateField(help_text='Ngày bắt đầu tiết kiệm', verbose_name='Ngày bắt đầu')),
                ('target_date', models.DateField(help_text='Ngày mong muốn đạt được mục tiêu', verbose_name='Ngày đích')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('categories_to_reduce', models.ManyToManyField(blank=True, help_text='Chọn các danh mục chi tiêu bạn muốn cắt giảm (cafe, trà sữa, ...)', to='ep1.category', verbose_name='Danh mục cần cắt giảm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Mục tiêu tiết kiệm',
                'verbose_name_plural': 'Mục tiêu tiết kiệm',
                'ordering': ['-created_at'],
            },
        ),
    ]
