# Generated by Django 5.2 on 2026-09-22 20:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep1', '0011_recurringincome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày phát sinh định kỳ'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='ep1.recurringexpense', verbose_name='Mẫu định kỳ'),
        ),
        migrations.AddField(
            model_name='income',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày phát sinh định kỳ'),
        ),
        migrations.AddField(
            model_name='income',
            name='recurring_income_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_incomes', to='ep1.recurringincome', verbose_name='Mẫu thu nhập định kỳ'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ngân sách'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số tiền đã tiết kiệm được', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền hiện tại'),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, help_text='Số tiền bạn muốn tiết kiệm', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền mục tiêu'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='budget_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_template__isnull', False)), fields=('recurring_template', 'occurrence_date'), name='unique_expense_per_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='income_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_income_template__isnull', False)), fields=('recurring_income_template', 'occurrence_date'), name='unique_income_per_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_income_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='savings_goal_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='savings_goal_current_non_negative'),
        ),
    ]
