# Generated by Django 5.2 on 2026-09-22 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep1', '0012_expense_occurrence_date_expense_recurring_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expense',
            name='unique_expense_per_occurrence',
        ),
        migrations.RemoveConstraint(
            model_name='income',
            name='unique_income_per_occurrence',
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('recurring_template', 'occurrence_date'), name='unique_expense_per_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(fields=('recurring_income_template', 'occurrence_date'), name='unique_income_per_occurrence'),
        ),
    ]
