# Generated by Django 5.2 on 2026-09-22 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep1', '0013_remove_expense_unique_expense_per_occurrence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expense_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='expense_user_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'date'], name='income_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'source'], name='income_user_source_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['user', 'is_active', 'next_due_date'], name='rec_exp_user_act_due_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringincome',
            index=models.Index(fields=['user', 'is_active', 'next_due_date'], name='rec_inc_user_act_due_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user', 'is_active'], name='savings_user_act_idx'),
        ),
    ]
